frappe.query_reports["Estado de Cuenta Operativo"] = {
    filters: [
        { fieldname: "position_type", label: __("Tipo"), fieldtype: "Select", options: "\nCobranza\nAplicación\nPartida complementaria\nCxC por ajuste" },
        { fieldname: "operational_status", label: __("Estado de conciliación"), fieldtype: "Autocomplete",
            description: __("Vacío: todos. Seleccione o escriba el estado exacto de la columna Estado de conciliación."),
            options: ["Conciliado", "Conciliada", "Parcial", "Pendiente", "Pendiente de confirmar", "Documentado",
                "Revisar distribución", "Sin conversión US$", "Detalle de empresa pendiente", "Detalle de empresa por aclarar",
                "Diferencia entre aplicación y depósito; requiere revisión", "Diferencia cambiaria en revisión",
                "Pendiente de detalle de la empresa", "Cobranza no deducida; revisar primera conciliación",
                "Depositado por la empresa; aplicación parcial en core", "Depósito parcial",
                "Aplicación parcial en core; depósito pendiente", "Aplicado en core; depósito pendiente",
                "Deducido; pendiente de aplicar en core", "Pendiente de conciliacion",
                "Registro contable verificado", "No conciliatoria", "Vigente", "Revertida", "Pendiente de cobro", "Parcialmente cobrada", "Revisar cobros"] },
        { fieldname: "client_number", label: __("Nro. Cliente"), fieldtype: "Data" },
        { fieldname: "national_id", label: __("Nro Cedula"), fieldtype: "Data" },
        { fieldname: "loan_number", label: __("Nro. Credito"), fieldtype: "Data" },
        { fieldname: "employer", label: __("Empresa"), fieldtype: "Link", options: "CN Employer" },
        { fieldname: "collection_cycle", label: __("Ciclo"), fieldtype: "Select", options: "\nMensual\nPrimera quincena\nSegunda quincena\nFecha exacta" },
        { fieldname: "from_month", label: __("Desde"), fieldtype: "Date" },
        { fieldname: "to_month", label: __("Hasta"), fieldtype: "Date" },
        { fieldname: "only_open", label: __("Solo pendientes"), fieldtype: "Check", default: 0 },
    ],
};
